name: szurop istván
favicon: null
layout_spectrum: 0.9736018453259021
typography_spectrum: 0.04783360892906785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4813023211900145
  lightness: 0.7209787557367235
  saturation: 0.3618409661576152
  rhythmicContrast: 0.023281700909137726
purpose: []
