name: szurop istván
favicon: null
layout_spectrum: 0.50385
typography_spectrum: 0.04783360892906785
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a2b3c7'
    - '#12242e'
    - '#587db2'
    - '#405536'
  brandStrength: 0.5
  lightness: 0.7209787557367235
  saturation: 0.3618409661576152
  rhythmicContrast: 0.023281700909137726
purpose: []
