name: szurop istván
favicon: null
layout_spectrum: 0.00289
typography_spectrum: 0.49807
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#a2b3c7'
    - '#12242e'
    - '#587db2'
    - '#405536'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
